from copy import deepcopy
from dataclasses import dataclass
from typing import Any

import jax
import jax.numpy as jnp
from jax import vmap

import momi3.sfs.events
from momi3.common import Axes, PopCounter
from momi3.event_tree import Population  # noqa: F401
from momi3.sfs.events import NoOp, Rename  # noqa: F401
import momi3.iicr.events

from .state import State


@dataclass(frozen=True, kw_only=True)
class Split1(momi3.sfs.events.Split1):
    def _setup_impl(
        self, in_axes: Axes, ns: PopCounter
    ) -> tuple[Axes, PopCounter, Any]:
        nsp = deepcopy(ns)
        nsp[self.recipient].update(nsp[self.donor])
        del nsp[self.donor]
        out_axes = in_axes.copy()
        del out_axes[self.donor]
        n = out_axes[self.recipient]
        del out_axes[self.recipient]
        # deleting and then re-adding ensures that recipient is the last axis.
        out_axes[self.recipient] = n
        aux = {"in_axes": in_axes, "out_axes": out_axes}
        return out_axes, nsp, aux

    def _execute_impl(self, st: State, params: dict, aux: Any) -> State:
        assert self.donor in aux["in_axes"]
        assert self.donor not in aux["out_axes"]
        assert self.recipient in aux["in_axes"]
        assert self.recipient in aux["out_axes"]
        i = list(aux["in_axes"]).index(self.recipient)
        j = list(aux["in_axes"]).index(self.donor)
        k = list(aux["out_axes"]).index(self.recipient)

        def f(A):
            # sum of antidiagonals == convolution of two pops
            return jnp.array(
                [jnp.trace(A[:, ::-1], offset=i) for i in range(A.shape[0])]
            )[::-1]

        # rotate axes i and j to end, apply f to stack of mats, then rotate back
        for _ in range(st.p.ndim - 2):
            f = vmap(f)
        p_prime = f(jnp.moveaxis(st.p, (i, j), (-2, -1)))
        p_prime = jnp.moveaxis(p_prime, -1, k)
        return st._replace(p=p_prime)


@dataclass(frozen=True, kw_only=True)
class Split2(momi3.sfs.events.Split2):
    def _setup_impl(
        self, in_axes: dict[str, Axes], ns: PopCounter
    ) -> tuple[Axes, PopCounter, Any]:
        out_axes, nsp, aux = super()._setup_impl(in_axes, ns)
        # number of lineages stays same
        out_axes[self.recipient] = in_axes["donor_axes"][self.donor]
        return out_axes, nsp, aux

    def _execute_impl(self, state: dict[str, State], params: dict, aux: Any) -> State:
        """Merge two populations in different event blocks.

        Args:
            st: state just before the merge event
            params: dict of parameters
            aux: dict of auxiliary data generated by setup
        """
        donor_st = state["donor_state"]
        recip_st = state["recipient_state"]
        donor_axes = aux["donor_axes"]
        recip_axes = aux["recip_axes"]
        n = donor_st.p.shape[0]
        assert donor_st.p.shape == (n,) * len(donor_axes)
        assert recip_st.p.shape == (n,) * len(recip_axes)
        da = list(donor_axes)
        ra = list(recip_axes)
        i = da.index(self.donor)
        j = ra.index(self.recipient)

        def f(donor_col):
            def g(recip_col):
                a, b, c = jnp.ogrid[:n, :n, :n]
                # TODO this is a convolution
                r = jnp.sum((donor_col[a] * recip_col[b]) * (a + b == c), axis=(0, 1))
                return r

            return jnp.apply_along_axis(g, j, recip_st.p)

        p_prime = jnp.apply_along_axis(f, -1, jnp.moveaxis(donor_st.p, i, -1))
        # the effect of applying along ith axis of donor,
        # and jth axis of recip
        p_prime_axes = da[:i] + da[i + 1 :] + ra
        assert tuple(p_prime_axes) == tuple(aux["out_axes"])
        return State(
            p=p_prime,
            s=donor_st.s * recip_st.s,
            c=donor_st.c + recip_st.c,
            t=donor_st.t,  # t is the same for both populations
            terminal=False,
        )


@dataclass(frozen=True, kw_only=True)
class MigrationStart(momi3.sfs.events.MigrationStart):
    def _setup_impl(
        self, in_axes: Axes, ns: PopCounter
    ) -> tuple[Axes, PopCounter, Any]:
        out_axes, nsp, aux = super()._setup_impl(in_axes, ns)
        # out_axes = src_ax | dst_ax
        aux.update({"in_axes": in_axes, "out_axes": out_axes})
        return out_axes, nsp, aux

    def _execute_impl(self, state: dict[str, State], params: dict, aux: Any) -> State:
        # merge the two population tensors into one
        src_st = state["source_state"]
        dst_st = state["dest_state"]
        # an empty/scalar tensor represents one deme with no lineages
        d2 = len(aux["in_axes"]["dest_axes"])
        p_prime = src_st.p[(...,) + (None,) * d2] * dst_st.p
        return State(
            p=p_prime,
            s=src_st.s * dst_st.s,
            c=src_st.c + dst_st.c,
            t=src_st.t,  # t is the same for both populations
            terminal=False,
        )


@dataclass(frozen=True, kw_only=True)
class Admix(momi3.sfs.events.Admix):
    def _setup_impl(
        self, in_axes: Axes, ns: PopCounter
    ) -> tuple[Axes, PopCounter, Any]:
        out_axes, nsp, aux = super()._setup_impl(in_axes, ns)
        aux.update({"in_axes": in_axes, "out_axes": out_axes})
        return out_axes, nsp, aux

    def _execute_impl(self, st: State, params: dict, aux: Any) -> State:
        p_admix = self.f_p(params)
        # child splits into self.parent1 and self.parent2
        i = list(aux["in_axes"]).index(self.child)
        j, k = [list(aux["out_axes"]).index(x) for x in (self.parent1, self.parent2)]
        # rotate axis i to back and vmap over it
        n = st.p.shape[0]
        assert st.p.shape == (n,) * st.p.ndim

        def f(v):
            # v is the distribution of lineages in the child
            # i is the number of lineages in the child
            # j is the number of lineages in the first parent
            # k is the number of lineages in the second parent
            i, j, k = jnp.ogrid[:n, :n, :n]
            M = v[i] * jax.scipy.stats.binom.pmf(j, i, p_admix) * (k == i - j)
            return M.sum(0)

        for _ in range(st.p.ndim - 1):
            f = vmap(f)
        p_prime = f(jnp.moveaxis(st.p, i, -1))
        p_prime = jnp.moveaxis(p_prime, (-2, -1), (j, k))
        return st._replace(p=p_prime)


@dataclass(frozen=True, kw_only=True)
class Pulse(momi3.sfs.events.Pulse):
    def _setup_impl(
        self, in_axes: Axes, ns: PopCounter
    ) -> tuple[Axes, PopCounter, Any]:
        out_axes, nsp, aux = super()._setup_impl(in_axes, ns)
        out_axes = in_axes
        # as in Admix, don't have to enlarge the number of ancestral lineages here
        aux["out_axes"] = out_axes
        return out_axes, nsp, aux

    def _execute_impl(self, st: State, params: dict, aux: Any) -> State:
        p_pulse = self.f_p(params)
        n = st.p.shape[0]
        assert st.p.shape == (n,) * st.p.ndim

        def f(M):
            # M is the joint distribution of source and dest.
            # now compute the joint distribution after the pulse:
            # i: number of lineages in source
            # j: number of lineages in dest
            # k: number of lineages donated
            # ret[i,j] = \sum_k M[i+k,j-k] * binom(i, k, p_pulse)
            (
                i,
                j,
                k,
            ) = jnp.ogrid[:n, :n, :n]
            mask = ((i + k) < n) & ((j - k) >= 0)
            S = M[i + k, j - k] * jax.scipy.stats.binom.pmf(k, i + k, p_pulse) * mask
            return S.sum(2)

        for _ in range(st.p.ndim - 2):
            f = vmap(f)

        i = list(aux["in_axes"]).index(self.source)
        j = list(aux["in_axes"]).index(self.dest)
        p_prime = f(jnp.moveaxis(st.p, (i, j), (-2, -1)))
        p_prime = jnp.moveaxis(p_prime, (-2, -1), (i, j))
        return st._replace(p=p_prime)
