import jax
import jax.numpy as jnp
import momi3.sfs.events.lift
import networkx as nx
import numpy as np
import itertools as it
from functools import reduce
from copy import deepcopy
from jax.scipy.special import logsumexp
import diffrax as dfx

from typing import Any

from dataclasses import dataclass
from momi3.common import Axes, PopCounter, get_path
from .state import State


def _outer_sum(T: jax.Array) -> jax.Array:
    """Compute the outer sum of a tensor along its last axis."""
    return reduce(
        lambda a, b: a[..., None] + b[None, :],
        T[1:],
        T[0],
    )


def _mats(d, n):
    B = np.array(list(np.ndindex((n,) * d))).reshape((n,) * d + (d,))
    C = B * (B - 1) / 2
    # construct a tensor D[i1,...,id,j1,...,jd] = 1 if |i-j| = 1, 0 otherwise
    c1 = B[(...,) + (None,) * d + (slice(None),)]
    c2 = B
    # Neighborhood tensor
    N1 = np.abs(c1 - c2).sum(-1) == 2
    N2 = c1.sum(-1) == c2.sum(-1)
    N = N1 & N2
    # X[i,j,u,v] = 1 if iu == jv - 1, 0 otherwise
    X = c1 == c2 - 1
    # Y[i,j,u,v] = 1 if iu == jv + 1, 0 otherwise
    Y = c1 == c2 + 1
    return dict(B=B, C=C, N=N, X=X, Y=Y)


@dataclass(frozen=True, kw_only=True)
class Lift(momi3.sfs.events.Lift):
    def _setup_impl(
        self, child_axes: Axes, ns: PopCounter
    ) -> tuple[Axes, PopCounter, Any]:
        n = list(child_axes.values())[0]
        assert all(v == n for v in child_axes.values())
        # find cliques of migration populations
        G = nx.DiGraph()
        G.add_nodes_from(
            child_axes
        )  # add a node for each population in the child partial likelihood
        G.add_edges_from(self.migrations)
        migration_sets = [tuple(c) for c in nx.connected_components(G.to_undirected())]
        # refine migration sets to only consider who is migrating into who
        migration_sets1 = []
        for cc in migration_sets:
            if len(cc) == 1:
                # if there is no migration, lift the single population in isolation
                migration_sets1.append(cc[0])
                continue
            a = []
            for c1, c2 in it.product(cc, repeat=2):
                if G.has_edge(c1, c2):
                    a.append((c1, c2))
            migration_sets1.append(tuple(a))

        aux = {}
        aux["migration_sets"] = migration_sets1
        aux["axes"] = child_axes
        nsp = deepcopy(ns)
        return child_axes, nsp, aux

    def _execute_impl(self, st: State, params: dict, aux: Any) -> State:
        """Lift partial likelihood.

        Args:
            st: state just before the lifting event
            params: dict of parameters
            aux: dict of auxiliary data generated by setup

        Returns:
            State after the lifting event.
        """
        t0, t1 = [get_path(params, t.path) for t in (self.t0, self.t1)]
        u = jnp.clip(st.t, t0, t1)
        t_isin_t0_t1 = (t0 <= st.t) & (st.t < t1)
        etas = self._etas(params)
        axes = aux["axes"]
        n = st.p.shape[0]
        d = st.p.ndim
        assert st.p.shape == (n,) * d

        if self.migrations == {} or self.terminal:
            # no migrations, so just lift each population to r and t1
            j = jnp.arange(n)
            C = j * (j - 1) // 2
            R = []
            for p in axes:
                R.append(etas[p].R(u) - etas[p].R(t0))
            R = jnp.array(R)
            cum_rates = C[:, None] * R[None, :]
            assert cum_rates.shape == (n, d)
            # convert to (n,) * d outer product tensor
            x = _outer_sum(cum_rates.T)
            assert x.shape == (n,) * d
            # probability of no coalescence
            log_p_nc = -x
            # use double where trick here. taking log(st.p) when st.p has zero entries
            # results in gradient nans!!
            p0 = jnp.isclose(st.p, 0.0)
            p_safe = jnp.where(p0, 1.0, st.p)
            log_p_prime = jnp.where(p0, -jnp.inf, jnp.log(p_safe) + log_p_nc)
            # end of double where trice
            s_prime = jnp.where(st.t < t0, 1.0, jnp.exp(logsumexp(log_p_prime)))
            p_prime = jnp.exp(log_p_prime - logsumexp(log_p_prime))
            # p_prime = probability distribution at u conditional on no coalescence
            coal = jnp.array([1 / 2 / etas[p](u) for p in axes])
            # iicr at time t, ignore if t is not in (t0, t1)
            y = _outer_sum(coal[:, None] * C[None, :])
            c_prime = jnp.where(t_isin_t0_t1, jnp.sum(p_prime * y), 0.0)
            return st._replace(
                p=p_prime, s=st.s * s_prime, c=st.c + c_prime, terminal=self.terminal
            )

        # p_dn = nd_to_dn(st.p)
        # st_dn = st._replace(p=p_dn)
        # st_prime_dn = momi3.iicr.events.lift_dn(st_dn, aux['axes'], M, etas, t0, t1)
        # p_prime = dn_to_nd(st_prime_dn.p)
        # assert p_prime.shape == st.p.shape
        # return st_prime_dn._replace(p=p_prime, terminal=self.terminal)

        # C[i1,...,id] = [i1(i1-1)/2, ..., id(id-1)/2]

        M = self._migration_matrix(params, aux["axes"])
        jump_ts = M.jump_ts
        solver = dfx.Tsit5()
        term = dfx.ODETerm(_term)
        eta_ts = jnp.concatenate([eta.t for eta in etas.values()])
        jump_ts = jnp.concatenate([jump_ts, eta_ts])
        jump_ts = jnp.sort(jump_ts)
        # final_subsaveat = dfx.SubSaveAt(t1=True)
        # evolving_subsaveat = dfx.SubSaveAt(ts=[u], fn=stats)
        saveat = dfx.SaveAt(t1=True, ts=[u], fn=_stats)
        ssc = dfx.PIDController(rtol=1e-6, atol=1e-6)
        mats = _mats(d, n)
        args = (etas, M, mats, aux["axes"])
        y0 = (st.p, 0.0)
        # Option I
        res = dfx.diffeqsolve(
            term,
            solver,
            t0=t0,
            t1=t1,
            dt0=(t1 - t0) / 100.0,
            # dt0=None,
            args=args,
            y0=y0,
            stepsize_controller=ssc,
            max_steps=16384,
            adjoint=dfx.RecursiveCheckpointAdjoint(),
            saveat=saveat,
        )
        (_, p1), (cu, _), (su, s1) = res.ys

        # Option II: scan
        # def body(accum, next_t):
        #     accum = eqx.internal.debug_backward_nan(accum, name="accum")
        #     (y, s), stats, t = accum
        #     b = jnp.isclose(t, u)
        #     stats = jax.tree.map(
        #         lambda u, v: jnp.where(b, u, v),
        #         _stats(t, (y, s), args),
        #         stats
        #     )
        #     delta_t = next_t - t
        #     dy, ds = _term(t, (y, s), args)
        #     y += dy * delta_t
        #     s += ds * delta_t
        #     return ((y, s), stats, next_t), None

        # ts = jnp.concatenate([jump_ts.clip(t0, t1), jnp.linspace(t0, t1, 1000), u[None]])
        # ts = jnp.sort(ts)
        # init = (y0, _stats(t0, y0, args), t0)
        # res, _ = jax.lax.scan(body, init, ts)

        # Option IIa (debugging only): loop
        # res = init
        # for t in ts:
        #     res, _ = body(res, t)
        # ((p1, s1), (pu, cu, su), _) = res

        p1 /= p1.sum()  # normalize to probability conditional on non-coalescence
        s_prime = jnp.where(st.t < t0, 1.0, 1.0 - su)
        c_prime = jnp.where(t_isin_t0_t1, cu, 0.0)
        return st._replace(
            p=p1, s=st.s * s_prime, c=st.c + c_prime, terminal=self.terminal
        )


def print_grad(x, message):
    @jax.custom_vjp
    def pg(x):
        return x

    def pg_fwd(x):
        return x, None

    def pg_bwd(_, x_grad):
        jax.debug.print(message + ": {}", x_grad, ordered=True)
        return (x_grad,)

    pg.defvjp(pg_fwd, pg_bwd)

    return pg(x)


def _rate(t, args):
    # y.shape = (n,) * d
    # y[i1,i2,...,id] = probability of deme 1 have i1 lineages, deme 2 have i2
    # lineages, etc.
    # the rate of coalescence in state (i1, i2, ..., id) is
    # \sum_k \binom{i_k}{2} / 2 / \eta_k(t)
    (etas, _, mats, axes) = args
    eta = jnp.array([1 / 2 / etas[pop](t) for pop in axes])
    # t, eta = print_grad((t, eta), "grad(t)/grad(eta)")
    # t, eta = eqx.internal.debug_backward_nan((t, eta), name="eta", terminate=False)
    return jnp.dot(mats["C"], eta)


def _stats(t, y, args):
    p, s = y
    p /= p.sum()
    c = jnp.sum(p * _rate(t, args))
    return (p, c, s)


def _term(t, y, args):
    # migration matrix at time t
    (etas, M, mats, axes) = args
    M_t = jnp.fill_diagonal(M(t), 0.0, inplace=False)
    # (t, M_t) = eqx.internal.debug_backward_nan((t, M_t), name="t/M_t", terminate=False)
    # transition p forward in time
    p, s = y
    # p = eqx.internal.debug_backward_nan(p, name="p", terminate=False)
    ds = p * _rate(t, args)
    # ds = eqx.internal.debug_backward_nan(ds, name="ds", terminate=False)
    # net rate of transition into state i=(i1,...,id) is
    # \sum_{j\in N(i)} p[j] \sum_{u,v} ju M[u,v] 1{ju == iu + 1, jv == iv - 1}
    # \sum_{j\in N(i)} p[j] \sum_{u,v} B[j,u] M[u,v] X[i,j,u] Y[i,j,v]
    # - N(i) are the neighbors of i (states reachable by one migration event)
    # - The tensors M, X, Y are defined to satisfy the above properties, e.g.
    #   B[j1,...,jd,u] = ju for u=1,...,d
    d = p.ndim
    i = tuple(range(d))
    j = tuple(range(d, 2 * d))
    u = 2 * d + 1
    v = u + 1
    dp_in = jnp.einsum(
        mats["N"],
        i + j,
        p,
        j,
        mats["B"],
        j + (u,),
        M_t,
        (u, v),
        mats["X"],
        i + j + (u,),
        mats["Y"],
        i + j + (v,),
        i,
    )
    # net rate of transition out of state (i1,...,id) due to migration is
    # p[i1,...,id] * \sum_k ik \sum_j M_{k,j}
    dp_out = jnp.einsum(p, i, mats["B"], i + (d + 1,), M_t, (d + 1, d + 2), i)
    dp = dp_in - dp_out
    # should have dp.sum() == 0 at this point, migration is conservative
    # movement into coalescent state
    dp -= ds
    # jax.debug.print("t:{} M_t:{} dp:{} ds:{}".format(t, M_t, dp, ds))
    # (t, M_t, dp, ds) = eqx.internal.debug_backward_nan((t, M_t, dp, ds), name="t/M_t/dp/ds")
    return dp, ds.sum()
