import itertools as it
from copy import deepcopy
from dataclasses import dataclass
from functools import reduce
from typing import Any

import diffrax as dfx
import jax
from jax.scipy.special import logsumexp
import jax.numpy as jnp
import networkx as nx
import numpy as np

import momi3.sfs.events
from momi3.common import Axes, PopCounter, get_path
from momi3.event_tree import Population  # noqa: F401
from momi3.sfs.events import NoOp, Rename  # noqa: F401

from .state import State


def _merge(p, j, k):
    "merge population j into population k"

    # this means merge tensor indices j into k along each axis
    def f(q, i):
        def g(v):
            return jnp.delete(v, j).at[k].add(v[j])

        return jnp.apply_along_axis(g, i, q)

    return reduce(f, range(p.ndim), p)


def _split(p, j, k1, k2, prob):
    "split population j into populations k1 and k2"
    if k1 > k2:
        return _split(p, j, k2, k1, 1 - prob)

    def f(q, i):
        def g(v):
            vj = v[j]
            v = jnp.delete(v, j)
            v = jnp.insert(v, k1, vj * prob)
            v = jnp.insert(v, k2, vj * (1 - prob))
            return v

        return jnp.apply_along_axis(g, i, q)

    ret = reduce(f, range(p.ndim), p)
    return ret


def _pulse(p, j, k, prob):
    "pulse population j into population k"

    def f(q, i):
        def g(v):
            return v.at[j].multiply(1 - prob).at[k].add(v[j] * prob)

        return jnp.apply_along_axis(g, i, q)

    return reduce(f, range(p.ndim), p)


def _product(p1, p2):
    # align two ndarrays for concatenation
    n = p1.ndim
    assert n == p2.ndim
    d1 = p1.shape[0] - 1
    assert p1.shape == (d1 + 1,) * n
    d2 = p2.shape[0] - 1
    assert p2.shape == (d2 + 1,) * n
    # ret = jnp.zeros((d1 + d2 + 1,) * n)
    inds = jnp.array(jnp.meshgrid(*[jnp.arange(d1 + d2 + 1)] * n, indexing="ij"))
    i1 = jnp.where(inds < d1, inds, -1)
    i2 = jnp.where((d1 <= inds) & (inds < d1 + d2), inds - d1, -1)
    p1f = p1[*i1]
    p2f = p2[*i2]
    return (p1f * p2f).reshape((d1 + d2 + 1,) * n)


@dataclass(frozen=True, kw_only=True)
class Lift(momi3.sfs.events.Lift):
    def _setup_impl(
        self, child_axes: Axes, ns: PopCounter
    ) -> tuple[Axes, PopCounter, Any]:
        d = len(child_axes)
        n = next(iter(child_axes.values()))
        assert all(v == n for v in child_axes.values())
        # state.p is a tensor of shape (d + 1, d + 1, ..., d + 1) with n dimensions
        # create a new tensor A of shape state.p.shape + (d,) such that
        # A[i1,...,in,j] = #[i == j for i in {i1,...,in}]
        inds = np.transpose(np.unravel_index(np.arange((d + 1) ** n), (d + 1,) * n))
        counts = jax.vmap(lambda b: jnp.bincount(b, length=d + 1))(inds).reshape(
            (d + 1,) * n + (d + 1,)
        )

        # find cliques of migration populations
        G = nx.DiGraph()
        G.add_nodes_from(
            child_axes
        )  # add a node for each population in the child partial likelihood
        G.add_edges_from(self.migrations)
        migration_sets = [tuple(c) for c in nx.connected_components(G.to_undirected())]
        # refine migration sets to only consider who is migrating into who
        migration_sets1 = []
        for cc in migration_sets:
            if len(cc) == 1:
                # if there is no migration, lift the single population in isolation
                migration_sets1.append(cc[0])
                continue
            a = []
            for c1, c2 in it.product(cc, repeat=2):
                if G.has_edge(c1, c2):
                    a.append((c1, c2))
            migration_sets1.append(tuple(a))

        aux = {}
        aux["migration_sets"] = migration_sets1
        aux["axes"] = child_axes
        aux["C"] = counts * (counts - 1) / 2
        nsp = deepcopy(ns)
        return child_axes, nsp, aux

    def _execute_impl(self, st: State, params: dict, aux: Any) -> State:
        """Lift partial likelihood.

        Args:
            st: state just before the lifting event
            params: dict of parameters
            aux: dict of auxiliary data generated by setup

        Returns:
            State after the lifting event.
        """
        n = st.p.ndim
        t0, t1 = [get_path(params, t.path) for t in (self.t0, self.t1)]
        u = jnp.clip(st.t, t0, t1)
        t_isin_t0_t1 = (t0 <= st.t) & (st.t < t1)
        etas = self._etas(params)
        axes = aux["axes"]
        d = st.p.shape[0]
        assert st.p.shape == (d,) * n
        C = aux["C"]

        if self.migrations == {} or self.terminal:
            # no migrations, so just lift each population to r and t1
            R = []
            for p in axes:
                R.append(etas[p].R(u) - etas[p].R(t0))
            # no coalescence allowed in the "untracked" deme
            R.append(0.0)
            R = jnp.array(R)
            x = C.dot(R)
            # probability of no coalescence
            log_p_nc = -x
            log_p_prime = jnp.log(st.p) + log_p_nc
            log_s_prime = jnp.where(st.t < t0, 0.0, logsumexp(log_p_prime))
            p_prime = jnp.exp(log_p_prime - log_s_prime)
            coal = jnp.array([1 / 2 / etas[p](u) for p in axes])
            coal = jnp.append(coal, 0.0)
            # probability distribution conditional on no coalescence
            c_prime = jnp.where(t_isin_t0_t1, jnp.sum(p_prime * C.dot(coal)), 0.0)
            # no change to p since the lineages do not migrate
            return st._replace(
                p=p_prime,
                log_s=st.log_s + log_s_prime,
                c=st.c + c_prime,
                terminal=self.terminal,
            )

        M = self._migration_matrix(params, aux["axes"])

        def rate(t, y, args):
            etas, C = args
            eta = jnp.array([1 / 2 / etas[pop](t) for pop in axes])
            eta = jnp.append(eta, 0.0)
            return C.dot(eta)

        def stats(t, y, args):
            p, s = y
            p /= p.sum()
            c = jnp.sum(p * rate(t, y, args))
            return (p, c, s)

        def f(t, y, args):
            # migration matrix at time t
            etas, C = args
            M_t = M(t)
            M_t = jnp.pad(
                M_t, ((0, 1), (0, 1)), constant_values=0.0
            )  # add untracked deme
            # transition p forward in time
            p, _ = y
            ds = p * rate(t, y, args)
            # multiply along each axis, equivalent of direct sum
            dp = sum(
                map(
                    lambda i: jnp.apply_along_axis(M_t.T.__matmul__, i, p),
                    range(n),
                )
            )
            # movement into coalescent state
            dp -= ds  # movement among migrant states, independent
            # jax.debug.print("p:{} c:{} dp:{} dc:{}", p, c, dp, dc)
            return dp, ds.sum()

        solver = dfx.Kvaerno3()
        term = dfx.ODETerm(f)
        eta_ts = jnp.concatenate([eta.t for eta in etas.values()])
        jump_ts = jnp.concatenate([M.jump_ts, eta_ts])
        jump_ts = jnp.sort(jump_ts)
        # final_subsaveat = dfx.SubSaveAt(t1=True)
        # evolving_subsaveat = dfx.SubSaveAt(ts=[u], fn=stats)
        saveat = dfx.SaveAt(ts=[u, t1], fn=stats)
        ssc = dfx.PIDController(jump_ts=jump_ts, rtol=1e-6, atol=1e-6)
        args = (etas, C)
        y0 = (st.p, 0.0)
        res = dfx.diffeqsolve(
            term,
            solver,
            t0=t0,
            t1=t1,
            dt0=(t1 - t0) / 1000,
            # dt0=None,
            args=args,
            y0=y0,
            stepsize_controller=ssc,
            max_steps=16384,
            saveat=saveat,
        )
        (_, p1), (cu, _), (su, s1) = res.ys
        p1 /= p1.sum()  # normalize to probability conditional on non-coalescence
        log_s_prime = jnp.where(st.t < t0, 0.0, jnp.log1p(-su))
        c_prime = jnp.where(t_isin_t0_t1, cu, 0.0)
        return st._replace(
            p=p1, log_s=st.log_s * log_s_prime, c=st.c + c_prime, terminal=self.terminal
        )


@dataclass(frozen=True, kw_only=True)
class Split1(momi3.sfs.events.Split1):
    def _setup_impl(
        self, in_axes: Axes, ns: PopCounter
    ) -> tuple[Axes, PopCounter, Any]:
        nsp = deepcopy(ns)
        nsp[self.recipient].update(nsp[self.donor])
        del nsp[self.donor]
        # resulting axes, same thing
        out_axes = in_axes.copy()
        del out_axes[self.donor]
        # deleting and then re-adding ensures that recipient is the last axis. this enables us to easily apply
        n = out_axes.pop(self.recipient)
        out_axes[self.recipient] = n
        aux = {"in_axes": in_axes, "out_axes": out_axes}
        return out_axes, nsp, aux

    def _execute_impl(self, st: State, params: dict, aux: Any) -> State:
        assert self.donor in aux["in_axes"]
        assert self.donor not in aux["out_axes"]
        assert self.recipient in aux["in_axes"]
        assert self.recipient in aux["out_axes"]
        j = list(aux["in_axes"]).index(self.donor)
        k = list(aux["out_axes"]).index(self.recipient)
        # remove the i'th entry from state.p, then add it to the j'th entry of what remains
        p_prime = _merge(st.p, j, k)
        return st._replace(p=p_prime)


@dataclass(frozen=True, kw_only=True)
class Split2(momi3.sfs.events.Split2):
    def _setup_impl(
        self, in_axes: Axes, ns: PopCounter
    ) -> tuple[Axes, PopCounter, Any]:
        n = next(iter(in_axes["donor_axes"].values()))
        assert all(v == n for d in in_axes.values() for v in d.values())
        out_axes, nsp, aux = super()._setup_impl(in_axes, ns)
        out_axes1 = {}
        # this reorders out_axes to match what comes out of _product
        # makes life a bit easier
        for d in ["recip_axes", "donor_axes"]:
            for k in aux[d]:
                if k in out_axes:
                    out_axes1[k] = n
        aux["out_axes"] = out_axes1
        return out_axes1, nsp, aux

    def _execute_impl(self, state: dict[str, State], params: dict, aux: Any) -> State:
        """Merge two populations in different event blocks.

        Args:
            st: state just before the merge event
            params: dict of parameters
            aux: dict of auxiliary data generated by setup
        """
        donor_st = state["donor_state"]
        recip_st = state["recipient_state"]
        p_prime = _product(recip_st.p, donor_st.p)
        # now want to merge the populations in donor and recip into one
        combined_axes = aux["recip_axes"] | aux["donor_axes"]
        j, k = [list(combined_axes).index(x) for x in (self.donor, self.recipient)]
        p_prime = _merge(p_prime, j, k)
        ca = list(combined_axes)
        ca.remove(self.donor)
        assert ca == list(aux["out_axes"])
        return State(
            p=p_prime,
            log_s=donor_st.log_s + recip_st.log_s,
            c=donor_st.c + recip_st.c,
            t=donor_st.t,  # t is the same for both populations
            terminal=False,
        )


@dataclass(frozen=True, kw_only=True)
class MigrationStart(momi3.sfs.events.MigrationStart):
    def _setup_impl(
        self, in_axes: Axes, ns: PopCounter
    ) -> tuple[Axes, PopCounter, Any]:
        out_axes, nsp, aux = super()._setup_impl(in_axes, ns)
        aux.update({"in_axes": in_axes, "out_axes": out_axes})
        return out_axes, nsp, aux

    def _execute_impl(self, state: dict[str, State], params: dict, aux: Any) -> State:
        # merge the two population tensors into one
        src_st = state["source_state"]
        dst_st = state["dest_state"]
        # an empty/scalar tensor represents one deme with no lineages
        p_prime = _product(src_st.p, dst_st.p)
        return State(
            p=p_prime,
            log_s=src_st.log_s * dst_st.log_s,
            c=src_st.c + dst_st.c,
            t=src_st.t,  # t is the same for both populations
            terminal=False,
        )


@dataclass(frozen=True, kw_only=True)
class Admix(momi3.sfs.events.Admix):
    def _setup_impl(
        self, in_axes: Axes, ns: PopCounter
    ) -> tuple[Axes, PopCounter, Any]:
        out_axes, nsp, aux = super()._setup_impl(in_axes, ns)
        # unlike sfs implementation, we don't have to "enlarge" the number of ancestral
        # lineages, because we track distribution over their location.
        out_axes[self.parent2] = out_axes[self.parent1]  # no extra lineages for parent1
        aux.update({"in_axes": in_axes, "out_axes": out_axes})
        return out_axes, nsp, aux

    def _execute_impl(self, st: State, params: dict, aux: Any) -> State:
        p_admix = self.f_p(params)
        # child splits into self.parent1 and self.parent2
        i = list(aux["in_axes"]).index(self.child)
        j, k = [list(aux["out_axes"]).index(x) for x in (self.parent1, self.parent2)]
        p_prime = _split(st.p, i, j, k, p_admix)
        return st._replace(p=p_prime)


@dataclass(frozen=True, kw_only=True)
class Pulse(momi3.sfs.events.Pulse):
    def _setup_impl(
        self, in_axes: Axes, ns: PopCounter
    ) -> tuple[Axes, PopCounter, Any]:
        out_axes = deepcopy(in_axes)
        aux = dict(in_axes=in_axes)
        nsp = deepcopy(ns)
        return out_axes, nsp, aux

    def _execute_impl(self, st: State, params: dict, aux: Any) -> State:
        p_pulse = self.f_p(params)
        i = list(aux["in_axes"]).index(self.dest)
        j = list(aux["in_axes"]).index(self.source)
        p_prime = _pulse(st.p, i, j, p_pulse)
        return st._replace(p=p_prime)
