import itertools as it
from copy import deepcopy
from dataclasses import dataclass
from functools import reduce
from typing import Any

import diffrax as dfx
import jax
from jax.scipy.special import logsumexp
import jax.numpy as jnp
import networkx as nx
import numpy as np

import momi3.sfs.events
from momi3.common import Axes, PopCounter, get_path
from momi3.event_tree import Population  # noqa: F401
from momi3.sfs.events import NoOp, Rename  # noqa: F401

from .state import State


def _merge(p, j, k):
    "merge population j into population k"

    def f(q, i):
        def g(v):
            return jnp.delete(v, j).at[k].add(v[j])

        return jnp.apply_along_axis(g, i, q)

    return reduce(f, range(p.ndim), p)


def _split(p, j, k1, k2, prob):
    "split population j into populations k1 and k2"

    def f(q, i):
        def g(v):
            return jnp.insert(
                jnp.delete(v, j),
                jnp.array([k1, k2]),
                jnp.array([v[j] * prob, v[j] * (1 - prob)]),
            )

        return jnp.apply_along_axis(g, i, q)

    return reduce(f, range(p.ndim), p)


def _pulse(p, j, k, prob):
    "pulse population j into population k"

    def f(q, i):
        def g(v):
            return v.at[j].multiply(1 - prob).at[k].add(v[j] * prob)

        return jnp.apply_along_axis(g, i, q)

    return reduce(f, range(p.ndim), p)


def _product(p1, d1, p2, d2):
    # align two ndarrays for concatenation
    n1 = p1.ndim
    n2 = p2.ndim
    if n1 > 0:
        p1 = jnp.pad(p1, [(0, d2)] * n1)
    if n2 > 0:
        p2 = jnp.pad(p2, [(d1, 0)] * n2)
    p1_sl = (slice(None),) * p1.ndim + (None,) * p2.ndim
    p2_sl = (None,) * p1.ndim + (slice(None),) * p2.ndim
    return p1[p1_sl] * p2[p2_sl]


@dataclass(frozen=True, kw_only=True)
class Lift(momi3.sfs.events.Lift):
    def _setup_impl(
        self, child_axes: Axes, ns: PopCounter
    ) -> tuple[Axes, PopCounter, Any]:
        d = len(child_axes)
        n = sum(a - 1 for p, a in child_axes.items())
        if n == 0:
            # NoOp lifting event
            return child_axes, ns, {}

        # state.p is a tensor of shape (d, d, ..., d) with n dimensions
        # create a new tensor A of shape state.p.shape + (d,) such that
        # A[i1,...,in,j] = #[i == j for i in {i1,...,in}]
        inds = np.transpose(np.unravel_index(np.arange(d**n), (d,) * n))
        counts = jax.vmap(lambda b: jnp.bincount(b, length=d))(inds).reshape(
            (d,) * n + (d,)
        )

        # find cliques of migration populations
        G = nx.DiGraph()
        G.add_nodes_from(
            child_axes
        )  # add a node for each population in the child partial likelihood
        G.add_edges_from(self.migrations)
        migration_sets = [tuple(c) for c in nx.connected_components(G.to_undirected())]
        # refine migration sets to only consider who is migrating into who
        migration_sets1 = []
        for cc in migration_sets:
            if len(cc) == 1:
                # if there is no migration, lift the single population in isolation
                migration_sets1.append(cc[0])
                continue
            a = []
            for c1, c2 in it.product(cc, repeat=2):
                if G.has_edge(c1, c2):
                    a.append((c1, c2))
            migration_sets1.append(tuple(a))

        aux = {}
        aux["migration_sets"] = migration_sets1
        aux["axes"] = child_axes
        aux["C"] = counts * (counts - 1) / 2
        nsp = deepcopy(ns)
        return child_axes, nsp, aux

    def _execute_impl(self, st: State, params: dict, aux: Any) -> State:
        """Lift partial likelihood.

        Args:
            st: state just before the lifting event
            params: dict of parameters
            aux: dict of auxiliary data generated by setup

        Returns:
            State after the lifting event.
        """
        n = st.p.ndim
        if n == 0:
            return st._replace(terminal=self.terminal)
        t0, t1 = [get_path(params, t.path) for t in (self.t0, self.t1)]
        u = jnp.clip(st.t, t0, t1)
        t_isin_t0_t1 = (t0 <= st.t) & (st.t < t1)
        etas = self._etas(params)
        axes = aux["axes"]
        d = st.p.shape[0]
        assert st.p.shape == (d,) * n
        C = aux["C"]

        if self.migrations == {} or self.terminal:
            # no migrations, so just lift each population to r and t1
            R = []
            for p in axes:
                R.append(etas[p].R(u) - etas[p].R(t0))
            R = jnp.array(R)
            x = C.dot(R)
            # probability of no coalescence
            log_p_nc = -x
            log_p_prime = jnp.log(st.p) + log_p_nc
            s_prime = jnp.where(st.t < t0, 1.0, jnp.exp(logsumexp(log_p_prime)).sum())
            p_prime = jnp.exp(log_p_prime - logsumexp(log_p_prime))
            coal = jnp.array([1 / 2 / etas[p](u) for p in axes])
            # probability distribution conditional on no coalescence
            c_prime = jnp.where(t_isin_t0_t1, jnp.sum(p_prime * C.dot(coal)), 0.0)
            # no change to p since the lineages do not migrate
            return st._replace(
                p=p_prime, s=st.s * s_prime, c=st.c + c_prime, terminal=self.terminal
            )

        M = self._migration_matrix(params, aux["axes"])

        def rate(t, y, args):
            etas, C = args
            eta = jnp.array([1 / 2 / etas[pop](t) for pop in axes])
            return C.dot(eta)

        def stats(t, y, args):
            p, s = y
            p /= p.sum()
            c = jnp.sum(p * rate(t, y, args))
            return (p, c, s)

        def f(t, y, args):
            # migration matrix at time t
            etas, C = args
            M_t = M(t)
            # transition p forward in time
            p, _ = y
            ds = p * rate(t, y, args)
            # multiply along each axis, equivalnt of direct sum
            dp = sum(
                map(
                    lambda i: jnp.apply_along_axis(M_t.T.__matmul__, i, p),
                    range(n),
                )
            )
            # movement into coalescent state
            dp -= ds  # movement among migrant states, independent
            # jax.debug.print("p:{} c:{} dp:{} dc:{}", p, c, dp, dc)
            return dp, ds.sum()

        solver = dfx.Kvaerno3()
        term = dfx.ODETerm(f)
        eta_ts = jnp.concatenate([eta.t for eta in etas.values()])
        jump_ts = jnp.concatenate([M.jump_ts, eta_ts])
        jump_ts = jnp.sort(jump_ts)
        # final_subsaveat = dfx.SubSaveAt(t1=True)
        # evolving_subsaveat = dfx.SubSaveAt(ts=[u], fn=stats)
        saveat = dfx.SaveAt(ts=[u, t1], fn=stats)
        ssc = dfx.PIDController(jump_ts=jump_ts, rtol=1e-6, atol=1e-6)
        args = (etas, C)
        y0 = (st.p, 0.0)
        res = dfx.diffeqsolve(
            term,
            solver,
            t0=t0,
            t1=t1,
            dt0=(t1 - t0) / 1000,
            # dt0=None,
            args=args,
            y0=y0,
            stepsize_controller=ssc,
            max_steps=16384,
            saveat=saveat,
        )
        (_, p1), (cu, _), (su, s1) = res.ys
        p1 /= p1.sum()  # normalize to probability conditional on non-coalescence
        s_prime = jnp.where(st.t < t0, 1.0, 1.0 - su)
        c_prime = jnp.where(t_isin_t0_t1, cu, 0.0)
        return st._replace(
            p=p1, s=st.s * s_prime, c=st.c + c_prime, terminal=self.terminal
        )


@dataclass(frozen=True, kw_only=True)
class Split1(momi3.sfs.events.Split1):
    def _setup_impl(
        self, in_axes: Axes, ns: PopCounter
    ) -> tuple[Axes, PopCounter, Any]:
        out_axes, nsp, _ = super()._setup_impl(in_axes, ns)
        aux = {"in_axes": in_axes, "out_axes": out_axes}
        return out_axes, nsp, aux

    def _execute_impl(self, st: State, params: dict, aux: Any) -> State:
        assert self.donor in aux["in_axes"]
        assert self.donor not in aux["out_axes"]
        assert self.recipient in aux["in_axes"]
        assert self.recipient in aux["out_axes"]
        j = list(aux["in_axes"]).index(self.donor)
        k = list(aux["out_axes"]).index(self.recipient)
        # remove the i'th entry from state.p, then add it to the j'th entry of what remains
        p_prime = _merge(st.p, j, k)
        return st._replace(p=p_prime)


@dataclass(frozen=True, kw_only=True)
class Split2(momi3.sfs.events.Split2):
    def _execute_impl(self, state: dict[str, State], params: dict, aux: Any) -> State:
        """Merge two populations in different event blocks.

        Args:
            st: state just before the merge event
            params: dict of parameters
            aux: dict of auxiliary data generated by setup
        """
        donor_st = state["donor_state"]
        recip_st = state["recipient_state"]
        out_axes = aux["out_axes"]
        donor_axes = aux["donor_axes"]
        recip_axes = aux["recip_axes"]
        d1 = len(recip_axes)
        d2 = len(donor_axes)
        p_prime = _product(recip_st.p, d1, donor_st.p, d2)
        # now want to merge the populations in donor and recip into one, to get
        # a square tensor of shape (d1 + d2 - 1,) * (n1 + n2)
        # new_p[i1,...,in,j] = sum_{k} recip_p[i1,...,in,k] * donor_p[k,j]
        combined_axes = aux["recip_axes"] | aux["donor_axes"]
        j, k = [list(combined_axes).index(x) for x in (self.donor, self.recipient)]
        p_prime = jnp.moveaxis(
            _merge(p_prime, j, k),
            k,
            list(out_axes).index(self.recipient),
        )
        return State(
            p=p_prime,
            s=donor_st.s * recip_st.s,
            c=donor_st.c + recip_st.c,
            t=donor_st.t,  # t is the same for both populations
            terminal=False,
        )


@dataclass(frozen=True, kw_only=True)
class MigrationStart(momi3.sfs.events.MigrationStart):
    def _setup_impl(
        self, in_axes: Axes, ns: PopCounter
    ) -> tuple[Axes, PopCounter, Any]:
        out_axes, nsp, aux = super()._setup_impl(in_axes, ns)
        aux.update({"in_axes": in_axes, "out_axes": out_axes})
        return out_axes, nsp, aux

    def _execute_impl(self, state: dict[str, State], params: dict, aux: Any) -> State:
        # merge the two population tensors into one
        src_st = state["source_state"]
        dst_st = state["dest_state"]
        # an empty/scalar tensor represents one deme with no lineages
        d1 = len(aux["in_axes"]["source_axes"])
        d2 = len(aux["in_axes"]["dest_axes"])
        p_prime = _product(src_st.p, d1, dst_st.p, d2)
        return State(
            p=p_prime,
            s=src_st.s * dst_st.s,
            c=src_st.c + dst_st.c,
            t=src_st.t,  # t is the same for both populations
            terminal=False,
        )


@dataclass(frozen=True, kw_only=True)
class Admix(momi3.sfs.events.Admix):
    def _setup_impl(
        self, in_axes: Axes, ns: PopCounter
    ) -> tuple[Axes, PopCounter, Any]:
        out_axes, nsp, aux = super()._setup_impl(in_axes, ns)
        # unlike sfs implementation, we don't have to "enlarge" the number of ancestral
        # lineages, because we track distribution over their location.
        out_axes[self.parent2] = 1  # no extra lineages for parent1
        assert out_axes.n == in_axes.n
        aux.update({"in_axes": in_axes, "out_axes": out_axes})
        return out_axes, nsp, aux

    def _execute_impl(self, st: State, params: dict, aux: Any) -> State:
        p_admix = self.f_p(params)
        # child splits into self.parent1 and self.parent2
        i = list(aux["in_axes"]).index(self.child)
        j, k = [list(aux["out_axes"]).index(x) for x in (self.parent1, self.parent2)]
        p_prime = _split(st.p, i, j, k, p_admix)
        return st._replace(p=p_prime)


@dataclass(frozen=True, kw_only=True)
class Pulse(momi3.sfs.events.Pulse):
    def _setup_impl(
        self, in_axes: Axes, ns: PopCounter
    ) -> tuple[Axes, PopCounter, Any]:
        out_axes, nsp, aux = super()._setup_impl(in_axes, ns)
        out_axes = in_axes
        # as in Admix, don't have to enlarge the number of ancestral lineages here
        aux["out_axes"] = out_axes
        return out_axes, nsp, aux

    def _execute_impl(self, st: State, params: dict, aux: Any) -> State:
        p_pulse = self.f_p(params)
        i = list(aux["in_axes"]).index(self.dest)
        j = list(aux["in_axes"]).index(self.source)
        p_prime = _pulse(st.p, i, j, p_pulse)
        return st._replace(p=p_prime)
